"""empty message

Revision ID: 926e071275cf
Revises: 
Create Date: 2024-08-17 10:45:38.492208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926e071275cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('administrator', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'administrator')
    # ### end Alembic commands ###
